config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  
  root 'home#index'
  
  resources :addresses
  resources :phones
  resources :contacts
  resources :types

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :contact
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :type
  has_one :address
  has_many :phones
  
  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true
  
  validates :nome, length: { in: 3..60 }, presence: true
  validates :email, length: { maximum: 40}, presence: true
  
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :contact
  
end

app/models/type.rb
class Type < ActiveRecord::Base
    has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_options_for_select, only: [:new, :edit, :update, :create]
  http_basic_authenticate_with name: "murilo", password: "1234", only: :destroy
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all.order(:nome).page(params[:page]).per(15)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address
    
  end

  # GET /contacts/1/edit
  def edit
    
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_path, notice: I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_options_for_select
      @type_options_for_select = Type.all
    end
    
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:nome, :email, :type_id, :rmk, 
      address_attributes: [:street, :city, :state],
      phones_attributes: [:id, :telephone, :_destroy])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:description)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
   ESTADOS_BRASILEIROS = [

    ["Acre", "AC"],

    ["Alagoas", "AL"],

    ["Amapá", "AP"],

    ["Amazonas", "AM"],

    ["Bahia", "BA"],

    ["Ceará", "CE"],

    ["Distrito Federal", "DF"],

    ["Espírito Santo", "ES"],

    ["Goiás", "GO"],

    ["Maranhão", "MA"],

    ["Mato Grosso", "MT"],

    ["Mato Grosso do Sul", "MS"],

    ["Minas Gerais", "MG"],

    ["Pará", "PA"],

    ["Paraíba", "PB"],

    ["Paraná", "PR"],

    ["Pernambuco", "PE"],

    ["Piauí", "PI"],

    ["Rio de Janeiro", "RJ"],

    ["Rio Grande do Norte", "RN"],

    ["Rio Grande do Sul", "RS"],

    ["Rondônia", "RO"],

    ["Roraima", "RR"],

    ["Santa Catarina", "SC"],

    ["São Paulo", "SP"],

    ["Sergipe", "SE"],

    ["Tocantins", "TO"]

  ]
    def mostrar_meu_nome
        "Murilo Henrique"
    end
    
    def options_for_states(selected)
        options_for_select(ESTADOS_BRASILEIROS, selected)
    end
    
    
  
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact, html: {class: "basic-grey"}) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= "#{pluralize(@contact.errors.count, "erro")} #{t('messages.errors')}: " %> </h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>Contacts</h1>
  
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br> 
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br>
    <%= f.collection_select(:type_id, @type_options_for_select, :id, :description) %>
  </div>
  
  <%= f.fields_for :address do |address_fields| %>
    
    <%= address_fields.label :street %><br>
    <%= address_fields.text_field :street%>
    
    <%= address_fields.label :city %><br>
    <%= address_fields.text_field :city%>
    
    <%= address_fields.label :state %><br>
    <%= address_fields.select :state, options_for_states(@contact.address.state) 
    %>
  
  <% end %>
  
  <div id="phones">
  
  <%= f.fields_for :phones do |phones_fields| %>
    <%= render partial: "phone_fields", locals: {f: phones_fields} %>
  <% end %>
    <div class="field">
      <%= f.label :phones, '<span class="glyphicon glyphicon-plus"></span>'.html_safe %><br>
      <%= link_to_add_association('[Adicionar Telefone]', f, :phones) %>
    </div>
  </div>
  
  <div class="field">
    <%= f.label :rmk %><br>
    <%= f.text_area :rmk %>
  </div>
  
  <div class="actions">
    <%= f.submit "Enviar", class: "button" %>
    <%= link_to t('messages.back'), contacts_path, class: "button" %>
  </div>
<% end %>

app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
    <%= link_to_remove_association('remover', f) %>
  </div>
</div>

app/views/contacts/edit.html.erb
<%= render 'form' %>

app/views/contacts/index.html.erb
<div class="basic-grey">
  <script> 
    $.notify("<%= notice %>", "success")
  </script>
  
  <h1><%= "#{t('messages.listing')} #{@contacts.model_name.human(count: @contacts.count)}" %> </h1>
  
  <table>
    <thead>
      <tr>
        <th><%= @contacts.model.human_attribute_name("name") %></th>
        <th><%= @contacts.model.human_attribute_name("type") %></th>
        <th colspan="2"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @contacts.each do |contact| %>
        <tr style="background-color:<%= cycle("white","#F7F7F7") %>">
          <td><%= link_to contact.nome, contact %></td>
          <td><%= contact.type.description %></td>
          <td><%= link_to t('buttons.edit'), edit_contact_path(contact), class: "btn btn-info" %></td>
          <td><%= link_to t('buttons.destroy'), contact, method: :delete, data: { confirm: t('messages.confirm') }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @contacts %>
  
  <br>
  
  <%= link_to t('buttons.new'), new_contact_path, class: "button" %>
  <%= link_to t('buttons.back'), home_index_path, class: "button" %>
</div>

app/views/contacts/new.html.erb
<%= render 'form' %>

app/views/contacts/show.html.erb
<div class="basic-grey">
  
  <p id="notice"><%= notice %></p>
  
  <p>
    <strong><%= t ('name') %>:</strong>
    <%= @contact.nome %>
  </p>
  
  <p>
    <strong><%= t ('email') %>:</strong>
    <%= @contact.email %>
  </p>
  
  <p>
    <strong><%= t ('tipo') %>:</strong>
    <%= t @contact.type.description  %>
  </p>
  
  <% @contact.phones.each do |contact| %>
    <p>
      <strong><%= t ('phone') %>:</strong>
      <%= contact.telephone %>
    </p>  
  
  <%end%>
  
  <p>
    <strong><%= t ('observação') %>:</strong>
    <%= @contact.rmk %>
  </p>
  
  
  <%= link_to 'Back', contacts_path, class: "button" %>
</div>

app/views/home/index.html.erb
<div class="basic-grey">
    <h1>Seja bem vindo à nossa agenda!</h1>
        
    <ul>
        <li><span class="glyphicon glyphicon-th-list"></span><%= link_to "Tipos", types_path  %></a></li>
        <li><span class="glyphicon glyphicon-phone-alt"></span><%= link_to "Contatos", contacts_path %></li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/types/_form.html.erb
<%= form_for(@type, html:{class:"basic-grey"}) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <h1> Types </h1>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "Enviar", class: "button" %>
    <%= link_to 'Back', types_path, class: "button" %>
  </div>
<% end %>

app/views/types/edit.html.erb
<%= render 'form' %>

app/views/types/index.html.erb
<div class="basic-grey">
  <p id="notice"><%= notice %></p>
  
  <h1><%= "#{t('messages.listing')} #{@types.model_name.human(count: @types.count) }" %></h1>
  
  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th colspan="2"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @types.each do |type| %>
        <tr>
          <td><%= link_to type.description, type %></td>
          <td><%= link_to t('buttons.edit'), edit_type_path(type), class: "btn btn-info" %></td>
          <td><%= link_to t('buttons.destroy'), type, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to t('buttons.new'), new_type_path, class:"button" %>
  <%= link_to t('buttons.back'), home_index_path, class:"button"%>
</div>

app/views/types/new.html.erb
<%= render 'form' %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @type.description %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>